### ISSUE TITLE
Canvas app version?

### ISSUE THREAD

**Issue by Danielx64** [SahilATech/MultiFilePreviewControl#1]
Hu

Would it be possible to have a canvas app version of this?

Cheers

**Comment by SahilATech** [comment]
I mainly work with D365, but I think we can make this work for Canvas apps too. Since Web API calls don't work in Canvas apps, you could try using a service account to pull in the file info instead. You'd need to set up the service account with the right access, and it should let you display and manage files similarly to how the PCF control does.

Just be sure to handle the authentication and permissions carefully to keep everything secure. If you have any questions or run into any issues, feel free to reach out—I'm happy to help!

Cheers!
